#!/bin/bash

echo
echo
echo "Files that are in $2, but not in $1:"
echo
git diff --color --name-only --diff-filter=A $1 $2 $3
echo
echo
echo "Files that are in $1, but not in $2:"
echo
git diff --color --name-only --diff-filter=A $2 $1 $3
echo
